name: MSYS2 GCC Package

on:
  pull_request:
  push:
  schedule:
    - cron: '30 2,8,15 * * *'
  workflow_dispatch:


jobs:
  main:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        gcc: [ mingw64, ucrt64 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: mingw

      - name: Update gcc
        timeout-minutes: 10
        run:  ruby create_gcc_pkg.rb ${{ matrix.gcc }}

      - name: upload asset
        timeout-minutes: 5
        uses: ./.github/actions/upload-binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_tag: 'msys2-gcc-pkgs'
          release_name: ${{ matrix.gcc }}
